const productos = [{name:"°Phala Paper Bag",price:169,id:"150",img:" ",color:"Naturbelassen",size:"Onesize",gender:"Unisex",categorie:"Bags", 
	description:"Klares Design bestehend aus einem aussergewöhnlichen Material mit dem Potenzial zum Lieblingsstück. Erlebe urbane Abenteuer und geniesse die Freiheit auf Reisen: Der stylische Rucksack mit noblem Charakter wird dein täglicher Begleiter sein. Der sportliche Rucksack ist wasserfest, extrem leicht, robust und reissfest. Das Innenfutter aus natürlichem Leinenstoff hat zwei Einstecktaschen und eine Reissverschlusstasche. Die Schultergurte bestehen aus einem angenehmen Baumwoll-Webbing und sind im Hand umdrehen verstellbar. Was für uns besonders essentiell ist: Unser stylischer Rucksack ist komplett ohne Tierprodukte, recyclebar und wird in Thun (Schweiz) hergestellt. Das innovative Papier stammt aus Deutschland, ist naturbelassen und stammt aus nachhaltiger Holzwirtschaft aus der EU. Die besten Voraussetzungen für ein hundertprozentig gutes Gewissen.Entfessle deine Kreativität und bemale deine Tasche mit wasserfesten Farben und mache sie zu deinem persönlichen Rucksack. Material: 98% Cellulose 2% Latex, Masse: L 61cm x T 12cm x B 38cm, Volumen 26 Liter, Gewicht: 470g. Frei von Pentachlorphenol (PCP) und Bisphenol A (BPA). Metallbestandteile sind nickel- und bleifrei. #Organic #Tagless #Recycelt"},,

// UNISEX: HOODIE
{name:"Hoodie °Khupa",price:79,id:"1",img:" ",color:"Schwarz",size:"Small",gender:"Unisex",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"2",img:" ",color:"Schwarz",size:"Medium",gender:"Unisex",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"3",img:" ",color:"Schwarz",size:"Large",gender:"Unisex",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"4",img:" ",color:"Schwarz",size:"XLarge",gender:"Unisex",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"5",img:" ",color:"Burgund",size:"Small",gender:"Unisex",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"6",img:" ",color:"Burgund",size:"Medium",gender:"Unisex",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"7",img:" ",color:"Burgund",size:"Large",gender:"Unisex",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"8",img:" ",color:"Burgund",size:"XLarge",gender:"Unisex",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"9",img:" ",color:"Weiss",size:"Small",gender:"Unisex",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Hoodie °Khupa",price:79,id:"10",img:" ",color:"Weiss",size:"Medium",gender:"Unisex",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"11",img:" ",color:"Weiss",size:"Large",gender:"Unisex",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"12",img:" ",color:"Weiss",size:"XLarge",gender:"Unisex",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"13",img:" ",color:"Grau",size:"Small",gender:"Unisex",categorie:"Hoodies", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"14",img:" ",color:"Grau",size:"Medium",gender:"Unisex",categorie:"Hoodies", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose,Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"15",img:" ",color:"Grau",size:"Large",gender:"Unisex",categorie:"Hoodies", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Hoodie °Khupa",price:79,id:"16",img:" ",color:"Grau",size:"XLarge",gender:"Unisex",categorie:"Hoodies", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose,Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,

// MEN: SWEATSHIRT
{name:"Sweatshirt °Tau",price:59,id:"17",img:" ",color:"Schwarz",size:"Small",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"18",img:" ",color:"Schwarz",size:"Medium",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"19",img:" ",color:"Schwarz",size:"Large",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"20",img:" ",color:"Schwarz",size:"XLarge",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"21",img:" ",color:"Burgund",size:"Small",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"22",img:" ",color:"Burgund",size:"Medium",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"23",img:" ",color:"Burgund",size:"Large",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"24",img:" ",color:"Burgund",size:"XLarge",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"25",img:" ",color:"Creme Weiss",size:"Small",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"26",img:" ",color:"Creme Weiss",size:"Medium",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"27",img:" ",color:"Creme Weiss",size:"Large",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"28",img:" ",color:"Creme Weiss",size:"XLarge",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"29",img:" ",color:"Forest Green",size:"Small",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"30",img:" ",color:"Forest Green",size:"Medium",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"31",img:" ",color:"Forest Green",size:"Large",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"32",img:" ",color:"Forest Green",size:"XLarge",gender:"Male",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,
{name:"Sweatshirt °Tau",price:59,id:"33",img:" ",color:"Grau",size:"Small",gender:"Male",categorie:"Sweatshirts", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Tau",price:59,id:"34",img:" ",color:"Grau",size:"Medium",gender:"Male",categorie:"Sweatshirts", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose,Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Tau",price:59,id:"35",img:" ",color:"Grau",size:"Large",gender:"Male",categorie:"Sweatshirts", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Tau",price:59,id:"36",img:" ",color:"Grau",size:"XLarge",gender:"Male",categorie:"Sweatshirts", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose,Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},,

// MEN: SHIRT
{name:"Shirt °Nare",price:39,id:"37",img:" ",color:"Schwarz",size:"Small",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"38",img:" ",color:"Schwarz",size:"Medium",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"39",img:" ",color:"Schwarz",size:"Large",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"40",img:" ",color:"Schwarz",size:"XLarge",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"41",img:" ",color:"Blau",size:"Small",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"42",img:" ",color:"Blau",size:"Medium",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"43",img:" ",color:"Blau",size:"Large",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"44",img:" ",color:"Blau",size:"XLarge",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"45",img:" ",color:"Grau",size:"Small",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"46",img:" ",color:"Grau",size:"Medium",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"47",img:" ",color:"Grau",size:"Large",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"48",img:" ",color:"Grau",size:"XLarge",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"49",img:" ",color:"Weiss",size:"Small",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"50",img:" ",color:"Weiss",size:"Medium",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"51",img:" ",color:"Weiss",size:"Large",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Nare",price:39,id:"52",img:" ",color:"Weiss",size:"XLarge",gender:"Male",categorie:"Shirts", description:"Material: 100% Bio-Baumwolle, Bio-In-Konversion, Gewicht: 140g/m2,#Sustainable #Soft #Organic"},

// WOMEN: HOODIE
{name:"Hoodie °Papala",price:79,id:"53",img:" ",color:"Schwarz",size:"Small",gender:"Female",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"54",img:" ",color:"Schwarz",size:"Medium",gender:"Female",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"55",img:" ",color:"Schwarz",size:"Large",gender:"Female",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"56",img:" ",color:"Schwarz",size:"XLarge",gender:"Female",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"57",img:" ",color:"Salbei",size:"Small",gender:"Female",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"58",img:" ",color:"Salbei",size:"Medium",gender:"Female",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"59",img:" ",color:"Salbei",size:"Large",gender:"Female",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"60",img:" ",color:"Salbei",size:"XLarge",gender:"Female",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"70",img:" ",color:"Creme Weiss",size:"Small",gender:"Female",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"71",img:" ",color:"Creme Weiss",size:"Medium",gender:"Female",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"72",img:" ",color:"Creme Weiss",size:"Large",gender:"Female",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"73",img:" ",color:"Creme Weiss",size:"XLarge",gender:"Female",categorie:"Hoodies", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"74",img:" ",color:"Grau",size:"Small",gender:"Female",categorie:"Hoodies", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"75",img:" ",color:"Grau",size:"Medium",gender:"Female",categorie:"Hoodies", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose,Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"76",img:" ",color:"Grau",size:"Large",gender:"Female",categorie:"Hoodies", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Hoodie °Papala",price:79,id:"77",img:" ",color:"Grau",size:"XLarge",gender:"Female",categorie:"Hoodies", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose,Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},

// WOMEN: SWEATSHIRT
{name:"Sweatshirt °Lebele",price:59,id:"78",img:" ",color:"Schwarz",size:"Small",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"79",img:" ",color:"Schwarz",size:"Medium",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"80",img:" ",color:"Schwarz",size:"Large",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"81",img:" ",color:"Schwarz",size:"XLarge",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"82",img:" ",color:"Salbei",size:"Small",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"83",img:" ",color:"Salbei",size:"Medium",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"84",img:" ",color:"Salbei",size:"Large",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"85",img:" ",color:"Salbei",size:"XLarge",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"86",img:" ",color:"Rosa",size:"Small",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"87",img:" ",color:"Rosa",size:"Medium",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"88",img:" ",color:"Rosa",size:"Large",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"89",img:" ",color:"Rosa",size:"XLarge",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"90",img:" ",color:"Weiss",size:"Small",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"91",img:" ",color:"Weiss",size:"Medium",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"92",img:" ",color:"Weiss",size:"Large",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"93",img:" ",color:"Weiss",size:"XLarge",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"94",img:" ",color:"Forest Green",size:"Small",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"95",img:" ",color:"Forest Green",size:"Medium",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"96",img:" ",color:"Forest Green",size:"Large",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2, #Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"97",img:" ",color:"Forest Green",size:"XLarge",gender:"Female",categorie:"Sweatshirts", description:"Material: 80% OCS-zertifizierte Bio- Baumwolle - 20% recyceltes RCS-Polyester Zertifiziert nach Standard 100 by OEKO-TEX, Bio-OCS, RCS-zertifiziert, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"98",img:" ",color:"Grau",size:"Small",gender:"Female",categorie:"Sweatshirts", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"99",img:" ",color:"Grau",size:"Medium",gender:"Female",categorie:"Sweatshirts", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose,Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"100",img:" ",color:"Grau",size:"Large",gender:"Female",categorie:"Sweatshirts", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose, Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},
{name:"Sweatshirt °Lebele",price:59,id:"101",img:" ",color:"Grau",size:"XLarge",gender:"Female",categorie:"Sweatshirts", description:"Material: 75% OCS-zertifizierte Bio-Baumwolle - 21% recyceltes RCS-Polyester - 4% Viskose,Gewicht: 280g/m2,#Organic #Tagless #Recycelt"},

// WOMEN: SHIRT
{name:"Shirt °Qwabi",price:39,id:"102",img:" ",color:"Schwarz",size:"Small",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 45g,,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"103",img:" ",color:"Schwarz",size:"Medium",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"104",img:" ",color:"Schwarz",size:"Large",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"105",img:" ",color:"Schwarz",size:"XLarge",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"106",img:" ",color:"Weiss",size:"Small",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"107",img:" ",color:"Weiss",size:"Medium",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"108",img:" ",color:"Weiss",size:"Large",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"109",img:" ",color:"Weiss",size:"XLarge",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"110",img:" ",color:"Grau",size:"Small",gender:"Female",categorie:"Shirts", description:"Material: 99% Baumwolle, 1% Viskose, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"111",img:" ",color:"Grau",size:"Medium",gender:"Female",categorie:"Shirts", description:"Material: 99% Baumwolle, 1% Viskose, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"112",img:" ",color:"Grau",size:"Large",gender:"Female",categorie:"Shirts", description:"Material: 99% Baumwolle, 1% Viskose, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"113",img:" ",color:"Grau",size:"XLarge",gender:"Female",categorie:"Shirts", description:"Material: 99% Baumwolle, 1% Viskose, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"114",img:" ",color:"Gold",size:"Medium",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"115",img:" ",color:"Gold",size:"Small",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"116",img:" ",color:"Gold",size:"Large",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"117",img:" ",color:"Gold",size:"XLarge",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},
{name:"Shirt °Qwabi",price:39,id:"118",img:" ",color:"Gold",size:"XLarge",gender:"Female",categorie:"Shirts", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 145g/m2,#Sustainable #Soft #Organic"},

// BEANIES: UNISEX
{name:"BEANIE °KOKOI",price:29,id:"119",img:" ",color:"Gelb",size:"Onesize",gender:"Unisex",categorie:"Beanie", description:"Material: Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 75g,Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},
{name:"BEANIE °KOKOI",price:29,id:"120",img:" ",color:"Grau",size:"Onesize",gender:"Unisex",categorie:"Beanie", description:"Material: Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 75g,Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},
{name:"BEANIE °KOKOI",price:29,id:"121",img:" ",color:"Blau",size:"Onesize",gender:"Unisex",categorie:"Beanie", description:"Material: Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 75g,Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},
{name:"BEANIE °KOKOI",price:29,id:"122",img:" ",color:"Schwarz",size:"Onesize",gender:"Unisex",categorie:"Beanie", description:"Material: Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 75g,Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},
{name:"BEANIE °KOKOI",price:29,id:"123",img:" ",color:"Grün",size:"Onesize",gender:"Unisex",categorie:"Beanie", description:"Material: Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 75g,Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},
{name:"BEANIE °KOKOI",price:29,id:"124",img:" ",color:"Burgund",size:"Onesize",gender:"Unisex",categorie:"Beanie", description:"Material: Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 75g,Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},,
{name:"BEANIE °KWENA",price:29,id:"125",img:" ",color:"Gelb",size:"Onesize",gender:"Unisex",categorie:"Beanie", description:"Material: Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 75g,Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},,
{name:"BEANIE °KWENA",price:29,id:"126",img:" ",color:"Grau",size:"Onesize",gender:"Unisex",categorie:"Beanie", description:"Material: Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 75g,Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},,
{name:"BEANIE °KWENA",price:29,id:"127",img:" ",color:"Blau",size:"Onesize",gender:"Unisex",categorie:"Beanie", description:"Material: Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 75g,Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},,
{name:"BEANIE °KWENA",price:29,id:"128",img:" ",color:"Schwarz",size:"Onesize",gender:"Unisex",categorie:"Beanie", description:"Material: Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 75g,Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},,
{name:"BEANIE °KWENA",price:29,id:"129",img:" ",color:"Grün",size:"Onesize",gender:"Unisex",categorie:"Beanie", description:"Material: Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 75g,Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},,
{name:"BEANIE °KWENA",price:29,id:"130",img:" ",color:"Burgund",size:"Onesize",gender:"Unisex",categorie:"Beanie", description:"Material: Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 75g,Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},,
{name:"HATS °NOKO",price:29,id:"131",img:" ",color:"Schwarz",size:"Onesize",gender:"Unisex",categorie:"Hats", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 69g/m2, Pflegehinweis: Handwaschen,  #Sustainable #Soft #Organic"},,
{name:"HATS °NOKO",price:29,id:"132",img:" ",color:"Burgund",size:"Onesize",gender:"Unisex",categorie:"Hats", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 69g/m2, Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},,
{name:"HATS °NOKO",price:29,id:"133",img:" ",color:"Grün",size:"Onesize",gender:"Unisex",categorie:"Hats", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 69g/m2, Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},,
{name:"HATS °NOKO",price:29,id:"134",img:" ",color:"Rosa",size:"Onesize",gender:"Unisex",categorie:"Hats", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 69g/m2, Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},,
{name:"HATS °NOKO",price:29,id:"135",img:" ",color:"Weiss",size:"Onesize",gender:"Unisex",categorie:"Hats", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 69g/m2, Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},,
{name:"HATS °NOKO",price:29,id:"136",img:" ",color:"Blau",size:"Onesize",gender:"Unisex",categorie:"Hats", description:"Material: 100% Baumwolle, Zertifiziert nach Standard 100 by OEKO-TEX, Gewicht: 69g/m2, Pflegehinweis: Handwaschen,#Sustainable #Soft #Organic"},]

























